%% Setup locations
clc;
Location = ["Mersing","TasikKenyir"];
Location = arrayfun(@(x) regexprep(x, '[^a-zA-Z]', ''),Location);
Lat = [2.43,5.04];
Lon = [103.84,105.03];
Time = [datetime(2021,3,14)];
% Period = 24*7;
NewData = [];
%% Setup emission rate (Terada et al.,2020)
EmissionRate = readtable("EmissionRateTime.xlsx","Sheet","Table015 (Page 6)","VariableNamingRule","preserve");
EmissionRate.Properties.VariableNames(1) = "UTC";
StartDate = Time(1);
Duration = EmissionRate.("Duration(h)"); 
Emission1 =  EmissionRate.("137Cs");
Emission2 = EmissionRate.("131I");

UTCExplosion = StartDate + hours(cumsum(Duration));
UTCExplosion = [StartDate;UTCExplosion(1:end-1)];

EmissionTable = table(UTCExplosion,Duration,Emission1,Emission2,'VariableNames',["UTC","Duration","137Cs","131I"]);
EmissionTable.YYYY = year(EmissionTable.UTC);
EmissionTable.MM = month(EmissionTable.UTC);
EmissionTable.DD = day(EmissionTable.UTC);
EmissionTable.HH = hour(EmissionTable.UTC);
RunTimes = hours(EmissionTable.UTC(end)-EmissionTable.UTC(1:end-1));
RunTimes = [RunTimes;0];

EndDate = EmissionTable.UTC(end);

cd("C:\HYSPLIT\working");
EmissionTable = EmissionTable(:,["YYYY" "MM" "DD" "HH" "137Cs" "131I"]);
Emission1 = arrayfun(@(x) sprintf("%.1E",x),Emission1);
Emission2 = arrayfun(@(x) sprintf("%.1E",x),Emission2);
EmissionTable.Properties.VariableNames(end-1:end) = ["Cs-137","I-131p"];
EmissionTable(:,end-1) = table(Emission1);
EmissionTable(:,end) = table(Emission2);

EmissionTable=EmissionTable(:,["YYYY" "MM" "DD" "HH"]);
EmissionTable = arrayfun(@(x) sprintf("%02d",x),EmissionTable{:,:});
EmissionTable = [EmissionTable,RunTimes,Emission1,Emission2];
writematrix(EmissionTable,"Allday.txt","Delimiter"," ");
EmissionTable(2:end+1,:) = EmissionTable;
EmissionTable(:,5)=[];
EmissionTable(1,:) = ["YYYY" "MM" "DD" "HH" "Cs-137" "I-131p"];
writematrix(EmissionTable,"TeradaEmission.txt","Delimiter"," ");
%% Batch file 
%  metfileName(s,:) = "gdas1."+lower(string(month(Period_interval(s),"shortname")))+string(mod(year(Period_interval(s)),100))+".w"+string(ceil(day(Period_interval(s))./7));
cd("C:\HYSPLIT\working")
ctFile = './Helloworld.bat';

str_Start = extractAfter(sprintf("%d%02d%02d%02d",year(StartDate),month(StartDate),day(StartDate),hour(StartDate)),2);
str_End = extractAfter(sprintf("%d%02d%02d%02d",year(EndDate),month(EndDate),day(EndDate),hour(EndDate)),2);

for l = 1:numel(Location)
    for t = 1:numel(Time)

        fid = fopen(ctFile, 'w');

        if fid == -1
            error('Failed to open batch file.');
        end

        batchCommands = ["@echo off";...
            "setLocal EnableDelayedExpansion";...
            "set DIR=c:";...
            "set PGM=%DIR%\hysplit";...
            "   ";...
            "echo -90.0   -180.0  lat/lon of lower left corner   >ASCDATA.CFG";...
            "echo 1.0     1.0     lat/lon spacing in degrees    >>ASCDATA.CFG";...
            "echo 180     360     lat/lon number of data points >>ASCDATA.CFG";...
            "echo 2               default land use category     >>ASCDATA.CFG";...
            "echo 0.2             default roughness length (m)  >>ASCDATA.CFG";...
            "echo '%PGM%\bdyfiles\'  directory of files         >>ASCDATA.CFG"
            " ";...
            "echo ^&SETUP               >SETUP.CFG";...
            "echo maxdim = 2,          >>SETUP.CFG";...
            "echo delt = 5.0,          >>SETUP.CFG";...
            "echo khmax = 24,          >>SETUP.CFG";...
            "echo numpar = 1500,      >>SETUP.CFG";...
            "echo maxpar = 10000000,      >>SETUP.CFG";...
            "echo /                    >>SETUP.CFG";...
            "  ";...
            "REM ------------------------------------------------";...
            "   ";...
            "for /F ""tokens=1,2,3,4,5,6,7"" %%A in (Allday.txt) do (";...
            "    set YEAR=%%A";...
            "    set MONTH=%%B";...
            "    set DAY=%%C"
            "    set HOUR=%%D";...
            "    set RUN=%%E";...
            "    set SA=%%F";...
            "    set SB=%%G";...
            "echo !DAY!";...
            "echo !HOUR!";...
            "echo !SA!";...
            "echo !SB!";...
            sprintf("    echo %s %02d !DAY! !HOUR!            >CONTROL",extractBefore(str_Start,3),month(StartDate));...
            "    echo 2                       >>CONTROL";...
            sprintf("    echo %.2f %.2f 1.0    >>CONTROL",Lat(l),Lon(l));...
            sprintf("    echo %.2f %.2f 1.0    >>CONTROL",Lat(l),Lon(l));...
            "echo !RUN!"
            "    echo !RUN!                   >>CONTROL";...
            "    echo 0                       >>CONTROL";...
            "    echo 10000.0                 >>CONTROL";...
            "    echo 5                       >>CONTROL";...
            "    echo C:\Users\Admin\Desktop\MetData\gdas1\                      >>CONTROL";...
            "    echo gdas1.mar21.w2         >>CONTROL";...
            "    echo C:\Users\Admin\Desktop\MetData\gdas1\                      >>CONTROL";...
            "    echo gdas1.mar21.w3         >>CONTROL";...
            "    echo C:\Users\Admin\Desktop\MetData\gdas1\                      >>CONTROL";...
            "    echo gdas1.mar21.w4         >>CONTROL";...
            "    echo C:\Users\Admin\Desktop\MetData\gdas1\                      >>CONTROL";...
            "    echo gdas1.mar21.w5         >>CONTROL";...
            "    echo C:\Users\Admin\Desktop\MetData\gdas1\                      >>CONTROL";...
            "    echo gdas1.apr21.w1         >>CONTROL";...
            "    echo 2                       >>CONTROL";...
            "    echo RNUC                    >>CONTROL";...
            "    echo 1.0                     >>CONTROL";...
            "    echo !RUN!                     >>CONTROL";...
            "    echo 00 00 00 00 00          >>CONTROL";...
            "    echo NGAS                    >>CONTROL";...
            "    echo 1.0                     >>CONTROL";...
            "    echo !RUN!                    >>CONTROL";...
            "    echo 00 00 00 00 00          >>CONTROL";...
            "    echo 1                       >>CONTROL";...
            sprintf(("    echo %.2f %.2f              >>CONTROL"),Lat(l),Lon(l));...
            "    echo 0.05 0.05               >>CONTROL";...
            "    echo 20.0 30.0               >>CONTROL";...
            "    echo ./                      >>CONTROL";...
            "    echo TG_03!DAY!!HOUR!             >>CONTROL";...
            "    echo 2                       >>CONTROL";...
            "    echo 0 100                   >>CONTROL";...
            "    echo 00 00 00 00 00          >>CONTROL";...
            "    echo 00 00 00 00 00          >>CONTROL";...
            "    echo 00 03 00                >>CONTROL";...
            "    echo 2                       >>CONTROL";...
            "    echo 1.0 1.0 1.0             >>CONTROL";...
            "    echo 0.001 0.0 0.0 0.0 0.0   >>CONTROL";...
            "    echo 0.0 8.0E-05 8.0E-05     >>CONTROL";...
            "    echo 0.0                     >>CONTROL";...
            "    echo 0.0                     >>CONTROL";...
            "    echo 0.0 0.0 0.0             >>CONTROL";...
            "    echo 0.0 0.0 0.0 0.0 0.0     >>CONTROL";...
            "    echo 0.0 0.0 0.0             >>CONTROL";...
            "    echo 0.0                     >>CONTROL";...
            "    echo 0.0                     >>CONTROL";...
            "  ";...
            "    %PGM%\exec\hycs_std";...
            "   ";...
            "    REM ---- terminate day hour loop";...
            ")";...
            ")";...
            " ";...
            " ";...
            "rem ---------------------------------------------";...
            "  ";...
            "%PGM%\exec\condecay -1:1:11025.8:C137 -2:1:8.02330:I131 +eTeradaEmission +oCG_ +t031205";...
            " ";...
            "for /F ""tokens=1,2,3,4,5,6,7"" %%A in (Allday.txt) do (";...
            "set DAY=%%C";...
            "set HOUR=%%D";...
            "  %PGM%\exec\con2asc -d, -iCG_03!DAY!!HOUR! -oCG_03!DAY!!HOUR! -s1"
            "  %PGM%\exec\con2rem -iCG_03!DAY!!HOUR! -oDG_03!DAY!!HOUR! -s1 -t0 -d1 -aactivity_unit.txt";...
            "  %PGM%\exec\concsum -iDG_03!DAY!!HOUR! -oSG_03!DAY!!HOUR! -l -pDOSE";...
            "  echo Finished: !DAY! !HOUR!";...
            ")";...
            ")";...
            "  ";...
            "dir /b SG_??????.bin >merg_list.txt";...
            "%PGM%\exec\conmerge -imerg_list.txt -ofdnpp_total.bin";...
            "    ";...
            "%PGM%\exec\conavgpd -ifdnpp_total.bin -ofdnpp_sums.bin "+sprintf("-a%s -b%s -r1",str_Start,str_End);... %adjust str_StartDate,str_EndDate
            "    ";...
            "%PGM%\exec\con2asc -d, -ifdnpp_total.bin -ofdnpp_total -s1";...
            "%PGM%\exec\con2asc -d, -ifdnpp_sums.bin -ofdnpp_sums -s1"];

        for i = 1:length(batchCommands)
            fprintf(fid, "%s\n", batchCommands(i));
        end

        fclose(fid);
        system('Helloworld.bat');

        disp("Conc file will be read..");
        %%
        Conc = readtable("fdnpp_total.txt");
        Sums = readtable("fdnpp_sums.txt");
        Conc.UTC = datetime(Conc.YEAR,Conc.MO,Conc.DA,Conc.HR,0,0);
        Sums.UTC = datetime(Sums.YEAR,Sums.MO,Sums.DA,Sums.HR,0,0);
        Conc = movevars(Conc,"UTC","Before",1);
        Sums = movevars(Sums,"UTC","Before",1);
        Conc(:,["YEAR" "MO" "DA" "HR"])= [];
        Sums(:,["YEAR" "MO" "DA" "HR"])= [];

        Variable = Conc.Properties.VariableNames(4:end);
        ldata = groupsummary(Conc,"UTC",["max","mean","std"],Variable,IncludeMissingGroups=false);
        u = unique(Conc.UTC);
        [ConcCell,CentroidCell] = deal(cell(numel(u), 1));
        for d = 1:numel(u)
             ConcCell{d,:} = Conc(Conc.UTC==u(d),:);
             % RegionCell{d,:} = unique(ConcCell{d}.Region);
             % RegionCell{d,:} = nonzeros(unique(cat(2,ConcCell{d}.Region)));
             [c1,c2] = centroid(polyshape(ConcCell{d}.LAT,ConcCell{d}.LON)); %,Trajectory = Traj
             CentroidCell{d,:} = [c1,c2];
         end
        ldata.Concentration = ConcCell;
        % % ldata.RegionCell = RegionCell;
        ldata.Centroid = CentroidCell;
        % % ldata.Area = zeros(height(ldata),1);
       
        for i = 1:height(ldata)
            ldata.Area(i) = areaint(ldata.Concentration{i}.LAT,ldata.Concentration{i}.LON,wgs84Ellipsoid("km"));
        end

        NewData.(Location(l)).(sprintf("T%02d%02d%02d%02d",year(Time(t)),month(Time(t)),day(Time(t)),hour(Time(t)))).Concentration = Conc;
        NewData.(Location(l)).(sprintf("T%02d%02d%02d%02d",year(Time(t)),month(Time(t)),day(Time(t)),hour(Time(t)))).ldata = ldata;
        NewData.(Location(l)).(sprintf("T%02d%02d%02d%02d",year(Time(t)),month(Time(t)),day(Time(t)),hour(Time(t)))).Sums = Sums;
    end

end


disp('Complete.')
